# Generated by Django 5.2.7 on 2025-10-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_project_color_alter_task_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="hierarchy",
        ),
        migrations.AddField(
            model_name="task",
            name="level",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="task",
            name="root",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_descendants",
                to="api.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="api.task",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["root", "level"], name="api_task_root_id_bfe280_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__lte", 2)), name="task_max_level_2"
            ),
        ),
    ]
