# Generated by Django 5.2.7 on 2025-10-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_timeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="api.project",
            ),
        ),
    ]
