# Generated by Django 5.2.7 on 2025-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_timeentry_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
