# Generated by Django 5.2.7 on 2025-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_timeentry_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="duration_seconds",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
