# Generated by Django 5.2.7 on 2025-10-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_timeentry_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
