# Generated by Django 5.2.7 on 2025-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_seconds',
            field=models.IntegerField(default=0, editable=False, help_text='実際の累計作業時間(秒) - 完了したTime Entryの合計'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='タスクの見積もり作業時間(分)', null=True),
        ),
    ]
